version: "3.7"
services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      - RECYCLE=false
    ports:
      - 139:139
      - 445:445
    restart: unless-stopped
    healthcheck:
      disable: true
