version: "3.8"
services:
  koel:
    image: hyzual/koel
    container_name: koel
    ports:
      - 80:80
    env_file: .env
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=koel-database
    depends_on:
      - koel-database
  koel-mariadb:
    image: mariadb
    container_name: koel-database
    env_file: .env
