version: "3.8"
services:
  openstreamingplatform:
    image: deamos/openstreamingplatform
    container_name: openstreamingplatform
    env_file: .env
    environment:
      - REDIS_HOST=openstreamingplatform-redis
    ports:
      - 8080:80
      - 1935:1935
    volumes:
      - type: volume
        source: openstreamingplatform-var-www-data
        target: /var/www/
      - type: volume
        source: openstreamingplatform-opt-osp-db-data
        target: /opt/osp/db/
      - type: volume
        source: openstreamingplatform-usr-local-nginx-conf-data
        target: /usr/local/nginx/conf/
    restart: unless-stopped
  openstreamingplatform-redis:
    image: redis:6-alpine
    container_name: openstreamingplatform-redis
    restart: unless-stopped
volumes:
  openstreamingplatform-var-www-data:
    name: openstreamingplatform-var-www-data
  openstreamingplatform-opt-osp-db-data:
    name: openstreamingplatform-opt-osp-db-data
  openstreamingplatform-usr-local-nginx-conf-data:
    name: openstreamingplatform-usr-local-nginx-conf-data
