version: "3.7"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      - TZ=Asia/Manila
      - WEBPASSWORD=piholepassword
    volumes:
      - pihole-etc-pihole:/etc/pihole
      - pihole-etc-dnsmasq-d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
volumes:
  pihole-etc-pihole:
    name: pihole-etc-pihole
  pihole-etc-dnsmasq-d:
    name: pihole-etc-dnsmasq-d
