version: "3.8"
services:
  server:
    image: bxggs/orl-server
    container_name: orl-server
    ports:
      - 8080:8080
    restart: unless-stopped
  logger:
    build: bxggs/orl-logger
    container_name: orl-logger
    restart: unless-stopped
    volumes:
      - ./overrustlelogs.toml:/logger/overrustlelogs.toml
      - ./channels.json:/logger/channels.json
      - ${LOGS_PATH}:/logs
