logHost = "http://localhost:8080"
maxOpenLogs = 1000

[twitch]
socketURL = "wss://irc-ws.chat.twitch.tv:443"
originURL = "http://irc-ws.twitch.tv"
clientID = ""
nick = ""
oauth = ""
admins = ["boggsbot"]
commandChannel = "boggsbot"
