version: "3.8"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53
      - 53:53/udp
      - 67:67/udp
      - 68:68
      # - 68:68/udp # doesn't work on my Pi 4
      - 80:80
      # - 443:443 # if HTTPs is enabled
      - 853:853
      # - 3000:3000 # for initial setup only
    volumes:
      - adguardhome-work:/opt/adguardhome/work
      - adguardhome-conf:/opt/adguardhome/conf
    restart: unless-stopped
volumes:
  adguardhome-work:
    name: adguardhome-work
  adguardhome-conf:
    name: adguardhome-conf
