version: "3.8"
services:
  surfshark:
    image: bxggs/surfshark
    container_name: surfshark
    env_file: .env
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    dns:
      - 1.1.1.1
