version: "3.8"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    env_file: .env
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
