version: "3.7"
services:
  transmission:
    volumes:
      - /path/to/config:/config
      - /path/to/downloads/complete:/downloads/complete
      - /path/to/downloads/incomplete:/downloads/incomplete
      - /path/to/watch:/watch
